name: GitHub Release
on:
  push:
    branches:
      - main
      
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Initialize git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Just in case they're duplicate tag names
        run: git fetch --prune --prune-tags origin && git pull origin $CI_BUILD_REF_NAME
      # - name: Create new branch for new release
      #   run: git checkout -b feature/new-release
      - name: run release
        run: npm run release:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: End Message
        run: echo 'Release is done!'
